# Generated by Django 2.2.2 on 2020-04-25 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time of the object creation', verbose_name='created at')),
                ('last_interaction', models.DateTimeField(auto_now=True, help_text='Date time of the last user message', verbose_name='updated at')),
                ('has_interaction', models.BooleanField(default=False, verbose_name='multi-message')),
                ('last_postback', models.CharField(default='', help_text='stores last postback message to speed interactions', max_length=50)),
                ('user', models.ForeignKey(help_text='Interacts with bot and make requests', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='users.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time of the object creation', verbose_name='created at')),
                ('content', models.CharField(max_length=50, verbose_name='message content')),
                ('is_postback', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bot.Conversation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
